spring.application.name=auth-server-projekt2
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.jwt.key-id=${JWT_KEY_ID:jwt-key-1}
app.jwt.public-key=${JWT_PUBLIC_KEY}
app.jwt.private-key=${JWT_PRIVATE_KEY}
server.forward-headers-strategy=framework
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.public-key-location=file:/etc/secrets/public.pem
spring.security.oauth2.resourceserver.jwt.private-key-location=file:/etc/secrets/private.pem